# Generated by Django 4.0.4 on 2022-09-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('Detail', models.TextField()),
                ('Name_image', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
